// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type AuthProvider struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	ProviderName   string    `json:"provider_name"`
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Card struct {
	ID             string          `json:"id"`
	NoteID         string          `json:"note_id"`
	CardTemplateID string          `json:"card_template_id"`
	DueDate        sql.NullTime    `json:"due_date"`
	Stability      sql.NullFloat64 `json:"stability"`
	Difficulty     sql.NullFloat64 `json:"difficulty"`
	Interval       sql.NullInt64   `json:"interval"`
	Status         sql.NullString  `json:"status"`
	Reps           sql.NullInt64   `json:"reps"`
	Lapses         sql.NullInt64   `json:"lapses"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type CardTemplate struct {
	ID           string         `json:"id"`
	NoteTypeID   string         `json:"note_type_id"`
	TemplateName string         `json:"template_name"`
	FrontHtml    string         `json:"front_html"`
	BackHtml     string         `json:"back_html"`
	Css          sql.NullString `json:"css"`
	OwnerID      string         `json:"owner_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Deck struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	OwnerID     string         `json:"owner_id"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	CardCount   int64          `json:"card_count"`
}

type DeckCollaborator struct {
	ID        string    `json:"id"`
	DeckID    string    `json:"deck_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Note struct {
	ID         string    `json:"id"`
	DeckID     string    `json:"deck_id"`
	NoteTypeID string    `json:"note_type_id"`
	OwnerID    string    `json:"owner_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type NoteField struct {
	ID           string    `json:"id"`
	NoteID       string    `json:"note_id"`
	FieldName    string    `json:"field_name"`
	FieldContent string    `json:"field_content"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type NoteType struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	OwnerID     string         `json:"owner_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Rating struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Review struct {
	ID            string          `json:"id"`
	CardID        string          `json:"card_id"`
	ReviewTime    time.Time       `json:"review_time"`
	RatingID      sql.NullString  `json:"rating_id"`
	ReviewSeconds sql.NullInt64   `json:"review_seconds"`
	NewInterval   sql.NullInt64   `json:"new_interval"`
	NewStability  sql.NullFloat64 `json:"new_stability"`
	NewDifficulty sql.NullFloat64 `json:"new_difficulty"`
	NewDueDate    sql.NullTime    `json:"new_due_date"`
	SessionID     sql.NullString  `json:"session_id"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Session struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Mode          sql.NullString `json:"mode"`
	Name          sql.NullString `json:"name"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       sql.NullTime   `json:"end_time"`
	IsActive      bool           `json:"is_active"`
	SessionDeckID string         `json:"session_deck_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type SessionCard struct {
	ID          string         `json:"id"`
	SessionID   string         `json:"session_id"`
	CardID      string         `json:"card_id"`
	Status      sql.NullString `json:"status"`
	NextCramDue sql.NullTime   `json:"next_cram_due"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type SessionDeck struct {
	ID        string    `json:"id"`
	SessionID string    `json:"session_id"`
	DeckID    string    `json:"deck_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Team struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	OwnerID   string    `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TeamMember struct {
	ID        string    `json:"id"`
	TeamID    string    `json:"team_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	DisplayName  sql.NullString `json:"display_name"`
	IsVerified   bool           `json:"is_verified"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type UserEvent struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	EventType sql.NullString `json:"event_type"`
	StartDate time.Time      `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type UserSession struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
	IsRevoked bool           `json:"is_revoked"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type UserSetting struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	Theme                sql.NullString `json:"theme"`
	DailyNewCardsLimit   int64          `json:"daily_new_cards_limit"`
	NotificationsEnabled bool           `json:"notifications_enabled"`
	TutorialEnabled      bool           `json:"tutorial_enabled"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}
